### ISSUE TITLE
PT-BR Translation

### ISSUE THREAD

**Issue by nawarian** [EvercodeLab/php-guide#13]
Hi, guys.

Would like to know what you think about developing a PT-BR translation of this material.
I could help with it =)

**Comment by Rafael-BP** [comment]
I can help too :)

**Comment by memphys** [comment]
@nawarian @Rafael-BP if you can do it then you are totally welcome =)

**Comment by nawarian** [comment]
Great then.
We'll start in about 10 hours.

I'll create a `pt-br` under the `pages` folder and start working with @Rafael-BP

Is that ok?

**Comment by memphys** [comment]
@nawarian seems good to me, thanks!

**Comment by nawarian** [comment]
@memphys I was talking with a brasilian local community in here, github.com/phpsp (PHP São Paulo). And they'll shall help too.

By doing that we would work just as we do with the `phptherightway` project:
PHPSP would fork this project, create a PR onto its home-page adding a `Translations` title and the `pt-br` link which would lead to the translated page.

Are you okay with that?

Also `phptherightway` project has a subdomain `br.phptherightway.com` which keep the user on their domain. Will that be the way or something like it?

**Comment by memphys** [comment]
@nawarian we are totally okay with the translations and link. As for the domain, for now the project has only third level one on our main site. We can add one more level or come out with new domain name. If you have something on your mind, we can discuss it.

**Comment by nawarian** [comment]
Okay then.

For now it might be more practical to keep the link inside gh-pages. Later on we'll talk about that, right? =)

**Comment by memphys** [comment]
@nawarian yep, no problem)
